Repository cytechmobile/radicle-vscode-extension, pull requests merged in 2024-04, with the labels that each got.

#111 ci: speculative fix for flaky dep installs
  .github/workflows/ci.yaml
  .github/workflows/commit-linting.yaml
  .github/workflows/pr-linting.yaml
  CHANGELOG.md
Labels: chore

#110 fix(patch-detail): show the correct review author
  CHANGELOG.md
  src/webviews/src/components/PatchDetailActivity.vue
  src/webviews/src/components/PatchDetailRevision.vue
Labels: bug

#113 docs: update links to point to radicle
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  package.json
Labels: documentation

#122 docs(contributing): add new sections referencing zulip, issues, cloning
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#127 chore(repo): don't recommend deprecated vscode extension
  .vscode/extensions.json
Labels: chore
